[package]
name = "robusta-android-example"
version = "0.21.1"
authors = ["Elise Chouleur"]
edition = "2018"

[lib]
name = "robustaandroidexample"
crate-type = ["cdylib"]

[dependencies]
robusta_jni = { path = "../.", version = "0.21.1" }
jni = "^0.21.1"
android_logger = "^0"
log = "^0"
