[package]
name = "robusta-example"
version = "0.21.1"
authors = ["Giovanni Berti <dev.giovanniberti@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
robusta_jni = { path = "../.", version = "0.21.1" }
